public class Dog { 
    String name; 
    boolean ismale; 
    int numPuppies; 
    String Puppies[] = new String [4];


public void setName (String dogName){
    name = dogname;
}

public String [] showName(){
    return name;
}
public String bark(){
    return "woof! woof!";
}
public void setName(int numOfPuppies){
    numPuppies = numOfPuppies; 
}
public int showName(){
    
    return numPuppies; 
}
public void setPuppies(String[] Puppies){
    puppies = puppiesSet;
}
public String[] showPuppies(){ 
    return puppies; 
}

}
        







